export const SampleUsers = [
  {
    username: 'dshowl1',
    avatar: 'https://robohash.org/rerumsunta.jpg?size=500x500&set=set1',
    fullname: 'Dickie Showl',
    bio: 'Maternal care for unstable lie, fetus 2',
    email: 'dshowl1@shareasale.com',
    password: 'yHSHnlH',
    nfts: {},
  },
  {
    username: 'bsextie2',
    avatar: 'https://robohash.org/consecteturcorporisnon.jpg?size=500x500&set=set1',
    fullname: 'Bernardine Sextie',
    bio: 'Salter-Harris Type I physeal fracture of lower end of humerus, left arm, subsequent encounter for fracture with malunion',
    email: 'bsextie2@stanford.edu',
    password: '789cGf8ZER',
    nfts: {},
  },
  {
    username: 'mmcneely3',
    avatar: 'https://robohash.org/odioaliasaccusamus.jpg?size=500x500&set=set1',
    fullname: 'Micki McNeely',
    bio: 'Poisoning by other agents primarily affecting gastrointestinal system, accidental (unintentional), initial encounter',
    email: 'mmcneely3@alexa.com',
    password: '6BWOTesxdNNf',
    nfts: {},
  },
  {
    username: 'jjerosch4',
    avatar: 'https://robohash.org/mollitiaquibusdambeatae.jpg?size=500x500&set=set1',
    fullname: 'Janine Jerosch',
    bio: 'Maternal care for fetal problem, unspecified, unspecified trimester, fetus 4',
    email: 'jjerosch4@joomla.org',
    password: '60ivCsN2',
    nfts: {},
  },
  {
    username: 'tpre5',
    avatar: 'https://robohash.org/voluptatemvitaevoluptas.jpg?size=500x500&set=set1',
    fullname: 'Tiffie Pre',
    bio: 'Unspecified complication of liver transplant',
    email: 'tpre5@abc.net.au',
    password: 'BjjDPrF',
    nfts: {},
  },
  {
    username: 'jstetlye6',
    avatar: 'https://robohash.org/sitrepellendusmagnam.jpg?size=500x500&set=set1',
    fullname: 'Janith Stetlye',
    bio: 'Displaced transverse fracture of shaft of left radius, subsequent encounter for open fracture type I or II with routine healing',
    email: 'jstetlye6@gmpg.org',
    password: 'x34JO4pnAtr2',
    nfts: {},
  },
  {
    username: 'lmacsweeney7',
    avatar: 'https://robohash.org/rationeestex.jpg?size=500x500&set=set1',
    fullname: 'Livia MacSweeney',
    bio: 'Unspecified injury of unspecified external jugular vein, subsequent encounter',
    email: 'lmacsweeney7@webnode.com',
    password: 'gVeMBm',
    nfts: {},
  },
  {
    username: 'aloyns8',
    avatar: 'https://robohash.org/etquiesse.jpg?size=500x500&set=set1',
    fullname: 'Ardisj Loyns',
    bio: 'Nontraumatic intracerebral hemorrhage in hemisphere, subcortical',
    email: 'aloyns8@seesaa.net',
    password: 'oyVltuImJs3M',
    nfts: {},
  },
  {
    username: 'jstackbridge9',
    avatar: 'https://robohash.org/nostrumlaudantiumcommodi.jpg?size=500x500&set=set1',
    fullname: 'Jeralee Stackbridge',
    bio: 'Osteonecrosis due to drugs of radius, ulna and carpus',
    email: 'jstackbridge9@gravatar.com',
    password: 'lDRZLfG',
    nfts: {},
  },
  {
    username: 'scawthrona',
    avatar: 'https://robohash.org/totamnihillaborum.jpg?size=500x500&set=set1',
    fullname: 'Sibilla Cawthron',
    bio: 'Other superficial injuries of left thumb, subsequent encounter',
    email: 'scawthrona@meetup.com',
    password: 'UKpGdXrg',
    nfts: {},
  },
  {
    username: 'nguisob',
    avatar: 'https://robohash.org/molestiasaliquamipsam.jpg?size=500x500&set=set1',
    fullname: 'Noel Guiso',
    bio: 'Burn of third degree of multiple sites of right wrist and hand, subsequent encounter',
    email: 'nguisob@networkadvertising.org',
    password: '2s39M7Cn',
    nfts: {},
  },
  {
    username: 'ysallingc',
    avatar: 'https://robohash.org/autquoet.jpg?size=500x500&set=set1',
    fullname: 'Yelena Salling',
    bio: 'Complete lesion at C3 level of cervical spinal cord',
    email: 'ysallingc@merriam-webster.com',
    password: '3pKbS3n7PIOm',
    nfts: {},
  },
  {
    username: 'dquinneyd',
    avatar: 'https://robohash.org/laboreestaut.jpg?size=500x500&set=set1',
    fullname: 'Daloris Quinney',
    bio: 'Pedal cycle driver injured in collision with other nonmotor vehicle in traffic accident, sequela',
    email: 'dquinneyd@github.com',
    password: 'NUfLGu9xTWi',
    nfts: {},
  },
  {
    username: 'bchaziere',
    avatar: 'https://robohash.org/officiaquiet.jpg?size=500x500&set=set1',
    fullname: 'Bruis Chazier',
    bio: 'Burn of first degree of left shoulder, subsequent encounter',
    email: 'bchaziere@dedecms.com',
    password: 'kwWFIPfyPE',
    nfts: {},
  },
  {
    username: 'arobertetf',
    avatar: 'https://robohash.org/suntmolestiasnon.jpg?size=500x500&set=set1',
    fullname: 'Ardene Robertet',
    bio: 'Nondisplaced fracture of lateral malleolus of right fibula, sequela',
    email: 'arobertetf@purevolume.com',
    password: '8PbJBNBwPa2',
    nfts: {},
  },
  {
    username: 'mosgerbyg',
    avatar: 'https://robohash.org/estautlabore.jpg?size=500x500&set=set1',
    fullname: 'Margalo Osgerby',
    bio: 'Unspecified open wound of right index finger with damage to nail, subsequent encounter',
    email: 'mosgerbyg@state.gov',
    password: 'eJTmMv',
    nfts: {},
  },
  {
    username: 'egiacuboh',
    avatar: 'https://robohash.org/voluptatibusnecessitatibuspraesentium.jpg?size=500x500&set=set1',
    fullname: 'Eleonora Giacubo',
    bio: 'Retinopathy of prematurity, stage 3, bilateral',
    email: 'egiacuboh@tumblr.com',
    password: 'RpO2Kl3vE',
    nfts: {},
  },
  {
    username: 'dtrasei',
    avatar: 'https://robohash.org/voluptatibussintnam.jpg?size=500x500&set=set1',
    fullname: 'Daveta Trase',
    bio: 'Collapsed vertebra, not elsewhere classified, occipito-atlanto-axial region, initial encounter for fracture',
    email: 'dtrasei@gizmodo.com',
    password: 'XLs2QnrA1b8',
    nfts: {},
  },
  {
    username: 'etopj',
    avatar: 'https://robohash.org/quiaaboccaecati.jpg?size=500x500&set=set1',
    fullname: 'Elton Top',
    bio: 'Person injured while boarding or alighting from railway train or railway vehicle, initial encounter',
    email: 'etopj@exblog.jp',
    password: 'T6BTGx4',
    nfts: {},
  },
  {
    username: 'ksappk',
    avatar: 'https://robohash.org/voluptatumofficiaculpa.jpg?size=500x500&set=set1',
    fullname: 'Kristal Sapp',
    bio: 'Displaced transverse fracture of right patella, subsequent encounter for closed fracture with delayed healing',
    email: 'ksappk@fc2.com',
    password: 'ky7cBN4hT1Ij',
    nfts: {},
  },
  {
    username: 'cgail',
    avatar: 'https://robohash.org/eaeligendiut.jpg?size=500x500&set=set1',
    fullname: 'Carlos Gai',
    bio: 'Other fracture of upper end of left ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing',
    email: 'cgail@mayoclinic.com',
    password: 'QNENKFHUWBs',
    nfts: {},
  },
  {
    username: 'hsedworthm',
    avatar: 'https://robohash.org/impeditquisplaceat.jpg?size=500x500&set=set1',
    fullname: 'Hill Sedworth',
    bio: 'Bipolar disorder, current episode manic without psychotic features, moderate',
    email: 'hsedworthm@altervista.org',
    password: 'byIyUJzNiI',
    nfts: {},
  },
]

export const SampleNfts = [
  {
    name: 'Flatcrown Buckwheat',
    imageUrl: 'https://robohash.org/eaeiusneque.jpg?size=500x500&set=set1',
    description:
      'Introduction of Other Diagnostic Substance into Ear, Via Natural or Artificial Opening',
    price: 73.5,
    forSale: false,
    ownerId: 'xxx', // change to real userId generated from cuid()
    stock: 18,
    supply: 18,
  },
  {
    name: 'Klamath Rockcress',
    imageUrl: 'https://robohash.org/oditquiaquas.jpg?size=500x500&set=set1',
    description: 'Excision of Left Ovary, Percutaneous Approach, Diagnostic',
    price: 8.0,
    forSale: true,
    ownerId: 'xxx',
    stock: 38,
    supply: 56,
  },
  {
    name: 'Santa Rita Mountain Draba',
    imageUrl: 'https://robohash.org/iuresintmagnam.jpg?size=500x500&set=set1',
    description: 'Drainage of Subarachnoid Space, Open Approach',
    price: 49.51,
    forSale: true,
    ownerId: 'xxx',
    stock: 16,
    supply: 44,
  },
  {
    name: 'Polypody Fissidens Moss',
    imageUrl: 'https://robohash.org/reiciendisodioaut.jpg?size=500x500&set=set1',
    description: 'Revision of Autologous Tissue Substitute in Left Toe Phalanx, Open Approach',
    price: 90.6,
    forSale: true,
    ownerId: 'xxx',
    stock: 22,
    supply: 94,
  },
  {
    name: 'Lopsided Star Orchid',
    imageUrl: 'https://robohash.org/molestiaelaborumvoluptatum.jpg?size=500x500&set=set1',
    description:
      'Dilation of Left Ulnar Artery, Bifurcation, with Three Intraluminal Devices, Percutaneous Approach',
    price: 20.69,
    forSale: false,
    ownerId: 'xxx',
    stock: 64,
    supply: 92,
  },
  {
    name: 'Meadow Bistort',
    imageUrl: 'https://robohash.org/debitisfaciliset.jpg?size=500x500&set=set1',
    description:
      'Insertion of Endobronchial Valve into Left Lower Lobe Bronchus, Via Natural or Artificial Opening Endoscopic',
    price: 52.21,
    forSale: true,
    ownerId: 'xxx',
    stock: 28,
    supply: 8,
  },
  {
    name: 'Velvet Tree',
    imageUrl: 'https://robohash.org/aspernaturdeseruntvoluptas.jpg?size=500x500&set=set1',
    description: 'Excision of Sacrococcygeal Joint, Open Approach, Diagnostic',
    price: 42.01,
    forSale: true,
    ownerId: 'xxx',
    stock: 25,
    supply: 51,
  },
  {
    name: 'Curlyleaf Muhly',
    imageUrl: 'https://robohash.org/quisveritatisvelit.jpg?size=500x500&set=set1',
    description:
      'Drainage of Esophagogastric Junction, Percutaneous Endoscopic Approach, Diagnostic',
    price: 80.0,
    forSale: false,
    ownerId: 'xxx',
    stock: 66,
    supply: 53,
  },
  {
    name: "Browne's Savory",
    imageUrl: 'https://robohash.org/inautperspiciatis.jpg?size=500x500&set=set1',
    description: 'Removal of Infusion Device from Heart, Percutaneous Approach',
    price: 7.66,
    forSale: false,
    ownerId: 'xxx',
    stock: 73,
    supply: 87,
  },
  {
    name: 'Tropical Fimbry',
    imageUrl: 'https://robohash.org/ipsumevenietea.jpg?size=500x500&set=set1',
    description: 'Aural Rehabilitation Status Assessment',
    price: 46.24,
    forSale: true,
    ownerId: 'xxx',
    stock: 67,
    supply: 79,
  },
  {
    name: 'Natal Glorybower',
    imageUrl: 'https://robohash.org/repudiandaeteneturut.jpg?size=500x500&set=set1',
    description:
      'Dilation of Hepatic Artery with Two Drug-eluting Intraluminal Devices, Open Approach',
    price: 85.58,
    forSale: false,
    ownerId: 'xxx',
    stock: 73,
    supply: 67,
  },
  {
    name: 'Montane Peperomia',
    imageUrl: 'https://robohash.org/quidemcorporissapiente.jpg?size=500x500&set=set1',
    description:
      'Drainage of Right Pleural Cavity with Drainage Device, Percutaneous Endoscopic Approach',
    price: 25.19,
    forSale: true,
    ownerId: 'xxx',
    stock: 3,
    supply: 80,
  },
  {
    name: 'Sea Campion',
    imageUrl: 'https://robohash.org/illoaccusamusrepellendus.jpg?size=500x500&set=set1',
    description: 'Destruction of Sigmoid Colon, Percutaneous Endoscopic Approach',
    price: 44.31,
    forSale: false,
    ownerId: 'xxx',
    stock: 41,
    supply: 71,
  },
  {
    name: "Lemmon's Canarygrass",
    imageUrl: 'https://robohash.org/laboreiustominima.jpg?size=500x500&set=set1',
    description: 'Planar Nuclear Medicine Imaging of Whole Body using Technetium 99m (Tc-99m)',
    price: 50.93,
    forSale: true,
    ownerId: 'xxx',
    stock: 89,
    supply: 8,
  },
  {
    name: 'Santa Cruz Gooseberry',
    imageUrl: 'https://robohash.org/nemoverooccaecati.jpg?size=500x500&set=set1',
    description: 'Transfer Right Ear Skin, External Approach',
    price: 8.35,
    forSale: true,
    ownerId: 'xxx',
    stock: 97,
    supply: 74,
  },
  {
    name: 'Needlepod Rush',
    imageUrl: 'https://robohash.org/quianemosunt.jpg?size=500x500&set=set1',
    description:
      'Introduction of Other Therapeutic Substance into Peripheral Nerves and Plexi, Percutaneous Approach',
    price: 90.89,
    forSale: true,
    ownerId: 'xxx',
    stock: 52,
    supply: 79,
  },
  {
    name: "Curtiss' Beaksedge",
    imageUrl: 'https://robohash.org/voluptasnesciuntofficia.jpg?size=500x500&set=set1',
    description: 'Revision of Drainage Device in Facial Bone, External Approach',
    price: 28.37,
    forSale: false,
    ownerId: 'xxx',
    stock: 93,
    supply: 87,
  },
  {
    name: 'Harsh Dewberry',
    imageUrl: 'https://robohash.org/eumconsequunturullam.jpg?size=500x500&set=set1',
    description: 'Occlusion of Right External Iliac Artery, Percutaneous Approach',
    price: 57.49,
    forSale: false,
    ownerId: 'xxx',
    stock: 53,
    supply: 22,
  },
  {
    name: 'Joewood',
    imageUrl: 'https://robohash.org/etdoloreillum.jpg?size=500x500&set=set1',
    description: 'Reposition Hypoglossal Nerve, Percutaneous Endoscopic Approach',
    price: 79.16,
    forSale: false,
    ownerId: 'xxx',
    stock: 52,
    supply: 74,
  },
  {
    name: "Rattan's Beardtongue",
    imageUrl: 'https://robohash.org/indolorumrecusandae.jpg?size=500x500&set=set1',
    description:
      'Muscle Performance Treatment of Neurological System - Head and Neck using Assistive, Adaptive, Supportive or Protective Equipment',
    price: 1.36,
    forSale: true,
    ownerId: 'xxx',
    stock: 7,
    supply: 96,
  },
  {
    name: 'Heartleaf Groundcherry',
    imageUrl: 'https://robohash.org/consecteturdoloremquein.jpg?size=500x500&set=set1',
    description:
      'Occlusion of Right Main Bronchus with Extraluminal Device, Percutaneous Endoscopic Approach',
    price: 43.97,
    forSale: false,
    ownerId: 'xxx',
    stock: 33,
    supply: 27,
  },
  {
    name: 'Curlycup Gumweed',
    imageUrl: 'https://robohash.org/facereessesunt.jpg?size=500x500&set=set1',
    description:
      'Supplement Left Inguinal Lymphatic with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    price: 89.51,
    forSale: false,
    ownerId: 'xxx',
    stock: 76,
    supply: 40,
  },
]
